/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/AIgwud1AL5L
 */
import Link from "next/link"
import { Button } from "@/components/ui/button"

export function Component() {
  return (
    <div key="1" className="bg-[#1a1a1a] text-white font-sans">
      <header className="flex justify-between items-center p-6">
        <AppleIcon className="text-white w-8 h-8" />
        <nav className="flex space-x-4">
          <Link className="block" href="#">
            NEW
          </Link>
          <Link className="block" href="#">
            SHOP
          </Link>
          <Link className="block" href="#">
            CART
          </Link>
          <MenuIcon className="text-white w-6 h-6" />
        </nav>
      </header>
      <main className="px-6 py-8">
        <div className="grid grid-cols-2 gap-4">
          <div>
            <img
              alt="Air Jordan 1 Mid SE GC"
              className="w-full h-auto"
              height="400"
              src="/placeholder.svg"
              style={{
                aspectRatio: "400/400",
                objectFit: "cover",
              }}
              width="400"
            />
            <div className="flex justify-between items-center mt-4">
              <div>
                <span className="text-3xl font-bold">01/08</span>
                <ArrowRightIcon className="text-white w-6 h-6 ml-2" />
              </div>
              <div>
                <span className="text-sm uppercase tracking-widest">Color</span>
                <div className="flex space-x-2 mt-1">
                  <span className="block w-4 h-4 bg-blue-500 rounded-full" />
                  <span className="block w-4 h-4 bg-gray-500 rounded-full" />
                  <span className="block w-4 h-4 bg-yellow-500 rounded-full" />
                </div>
              </div>
            </div>
            <div className="mt-4">
              <div className="w-24 h-1 bg-yellow-500" />
            </div>
          </div>
          <div>
            <h1 className="text-6xl font-bold uppercase">Air Jordan 1 Mid SE GC</h1>
            <p className="mt-4 text-gray-400">
              Air Jordan Limited edition shoes produced in 2019. Has come with a new nuance, which is ready to amaze you
              during the match.
            </p>
            <div className="flex mt-4">
              <StarIcon className="text-yellow-500 w-5 h-5" />
              <StarIcon className="text-yellow-500 w-5 h-5" />
              <StarIcon className="text-yellow-500 w-5 h-5" />
              <StarIcon className="text-yellow-500 w-5 h-5" />
              <StarIcon className="text-yellow-500 w-5 h-5" />
            </div>
            <Button className="mt-4 bg-yellow-500 text-black" variant="default">
              Add to Cart
            </Button>
          </div>
        </div>
        <div className="flex justify-between items-center mt-16">
          <div className="flex-1">
            <DribbbleIcon className="text-white w-32 h-32" />
          </div>
          <div className="flex space-x-4">
            <FacebookIcon className="text-white w-6 h-6" />
            <TwitterIcon className="text-white w-6 h-6" />
            <InstagramIcon className="text-white w-6 h-6" />
          </div>
        </div>
      </main>
    </div>
  )
}


function AppleIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 20.94c1.5 0 2.75 1.06 4 1.06 3 0 6-8 6-12.22A4.91 4.91 0 0 0 17 5c-2.22 0-4 1.44-5 2-1-.56-2.78-2-5-2a4.9 4.9 0 0 0-5 4.78C2 14 5 22 8 22c1.25 0 2.5-1.06 4-1.06Z" />
      <path d="M10 2c1 .5 2 2 2 5" />
    </svg>
  )
}


function MenuIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>
  )
}


function ArrowRightIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="m12 5 7 7-7 7" />
    </svg>
  )
}


function StarIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2" />
    </svg>
  )
}


function DribbbleIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <path d="M19.13 5.09C15.22 9.14 10 10.44 2.25 10.94" />
      <path d="M21.75 12.84c-6.62-1.41-12.14 1-16.38 6.32" />
      <path d="M8.56 2.75c4.37 6 6 9.42 8 17.72" />
    </svg>
  )
}


function FacebookIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z" />
    </svg>
  )
}


function TwitterIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 4s-.7 2.1-2 3.4c1.6 10-9.4 17.3-18 11.6 2.2.1 4.4-.6 6-2C3 15.5.5 9.6 3 5c2.2 2.6 5.6 4.1 9 4-.9-4.2 4-6.6 7-3.8 1.1 0 3-1.2 3-1.2z" />
    </svg>
  )
}


function InstagramIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="20" height="20" x="2" y="2" rx="5" ry="5" />
      <path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z" />
      <line x1="17.5" x2="17.51" y1="6.5" y2="6.5" />
    </svg>
  )
}
